update ios and android versions
mixpanel/mixpanel-react-native pull request #175
Opened 2023-03-02 21:01 UTC by dneralla

2023-03-02 21:05 UTC, jaredmixpanel approved these changes

2023-03-03 19:22 UTC, jaredmixpanel requested changes

2023-03-03 19:22 UTC, jaredmixpanel commented on MixpanelReactNative.podspec
> +  s.dependency "Mixpanel-swift", '4.0.5'
@dneralla can you please try updating `s.platform = :ios, "9.0"` to `"11.0"` to see if that fixes CI?

2023-03-06 07:17 UTC, zihejia commented
close this one and use #176 instead

2023-03-06 07:17 UTC, closed without merging